[font]
normal = { family = "CaskaydiaMono Nerd Font ", style = "" }
size = 9

[window]
opacity = 1
padding = { x = 0, y = 0 }


[env]
TERM = "xterm-256color"

[general]
import = [
	"~/.config/alacritty/themes/themes/terminal_app.toml"
]
